name = "Littlewood"
version = "0.1.0"
defaultTargets = ["Littlewood"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "master"

[[require]]
name = "PrimeNumberTheoremAnd"
git = "https://github.com/AlexKontorovich/PrimeNumberTheoremAnd"
rev = "main"

[[lean_lib]]
name = "Littlewood"
