name = "Littlewood"
version = "0.1.0"
defaultTargets = ["Littlewood"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "fdddb3ea2c8c35de4455e033bc2a5df4d3a391ee"


[[lean_lib]]
name = "Littlewood"
